var opcodes =
    [
	{key: "iFail",
	 label: "i_fail",
	 args: []},
	{key: "iEnter",
	 label: "i_enter",
	 args: []},
	{key: "iSaveCut",
	 label:"i_save_cut",
	 args: []},
	{key: "iExit",
	 label:"i_exit",
	 args: []},
	{key: "iExitFact",
	 label:"i_exitfact",
	 args: []},
        {key: "iExitQuery",
         label:"i_exitquery",
         args: []},
        {key: "iCall",
	 label:"i_call",
	 args: ["functor"]},
	{key: "iDepart",
	 label:"i_depart",
	 args: ["functor"]},
	{key: "iCut",
	 label:"i_cut",
	 args: []},
	{key: "iUnify",
	 label:"i_unify",
	 args: []},
	{key: "bFirstVar",
	 label: "b_firstvar",
	 args:["slot"]},
	{key: "bArgVar",
	 label: "b_argvar",
	 args: ["slot"]},
	{key: "bVar",
	 label: "b_var",
	 args: ["slot"]},
	{key: "bPop",
	 label: "b_pop",
	 args: []},
	{key: "bAtom",
	 label: "b_atom",
	 args: ["atom"]},
	{key: "bFunctor",
	 label: "b_functor",
	 args: ["functor"]},
	{key: "hAtom",
	 label: "h_atom",
	 args: ["atom"]},
	{key: "hFirstVar",
	 label: "h_firstvar",
	 args: ["slot"]},
	{key: "hFunctor",
	 label: "h_functor",
	 args: ["functor"]},
	{key: "hPop",
	 label: "h_pop",
	 args: []},
	{key: "hVoid",
	 label: "h_void",
	 args: []},
	{key: "hVar",
	 label: "h_var",
	 args: ["slot"]},
	{key: "tryMeElse",
	 label: "try_me_else",
	 args: ["address"]},
	{key: "retryMeElse",
	 label: "retry_me_else",
	 args: ["address"]},
	{key: "trustMe",
	 label: "trust_me",
	 args: []},

	{key: "nop",
	 label: "nop",
	 args: []}
    ];

var map = {};

for (var i = 0; i < opcodes.length; i++)
{
    opcodes[i].opcode = i;
    map[opcodes[i].key] = opcodes[i];
}

module.exports = {opcodes:opcodes,
		  opcode_map: map};
