"use strict";
exports=module.exports;

// A reminder: yfx means an infix operator f, with precedence p, where the lhs has a precendece <= p and the rhs has a precedence < p.

module.exports = {":-": {prefix:{precedence: 1200, fixity: "fx"},
                         infix: {precedence: 1200, fixity: "xfx"}},
                  "?-": {prefix:{precedence: 1200, fixity: "fx"}},
                  "dynamic": {prefix:{precedence: 1150, fixity: "fx"}},
                  "discontiguous": {prefix:{precedence: 1150, fixity: "fx"}},
                  "initialization": {prefix:{precedence: 1150, fixity: "fx"}},
                  "meta_predicate": {prefix:{precedence: 1150, fixity: "fx"}},
                  "module_transparent": {prefix:{precedence: 1150, fixity: "fx"}},
                  "multifile": {prefix:{precedence: 1150, fixity: "fx"}},
                  "thread_local": {prefix:{precedence: 1150, fixity: "fx"}},
                  "volatile": {prefix:{precedence: 1150, fixity: "fx"}},
                  "\\+": {prefix:{precedence: 900, fixity: "fy"}},
                  "~": {prefix:{precedence: 900, fixity: "fx"}},
                  "?": {prefix:{precedence: 500, fixity: "fx"}},
                  "+": {prefix:{precedence: 200, fixity: "fy"},
                        infix:{precedence: 500, fixity: "yfx"}},
                  "-": {prefix:{precedence: 200, fixity: "fy"},
                        infix:{precedence: 500, fixity: "yfx"}},
                  "\\": {prefix:{precedence: 200, fixity: "fy"}},
                  "-->": {infix:{precedence: 1200, fixity: "xfx"}},
                  ";": {infix:{precedence: 1100, fixity: "xfy"}},
                  "|": {infix:{precedence: 1100, fixity: "xfy"}},
                  "->": {infix:{precedence: 1050, fixity: "xfy"}},
                  "*->": {infix:{precedence: 1050, fixity: "xfy"}},
                  ",": {infix:{precedence: 1000, fixity: "xfy"}},
                  ":=": {infix:{precedence: 990, fixity: "xfx"}},
                  "<": {infix:{precedence: 700, fixity: "xfx"}},
                  "=": {infix:{precedence: 700, fixity: "xfx"}},
                  "=..": {infix:{precedence: 700, fixity: "xfx"}},
                  "=@=": {infix:{precedence: 700, fixity: "xfx"}},
                  "=:=": {infix:{precedence: 700, fixity: "xfx"}},
                  "=<": {infix:{precedence: 700, fixity: "xfx"}},
                  "==": {infix:{precedence: 700, fixity: "xfx"}},
                  "=\\=": {infix:{precedence: 700, fixity: "xfx"}},
                  ">": {infix:{precedence: 700, fixity: "xfx"}},
                  ">=": {infix:{precedence: 700, fixity: "xfx"}},
                  "@<": {infix:{precedence: 700, fixity: "xfx"}},
                  "@=<": {infix:{precedence: 700, fixity: "xfx"}},
                  "@>": {infix:{precedence: 700, fixity: "xfx"}},
                  "@>=": {infix:{precedence: 700, fixity: "xfx"}},
                  "\\=": {infix:{precedence: 700, fixity: "xfx"}},
                  "\\==": {infix:{precedence: 700, fixity: "xfx"}},
                  "is": {infix:{precedence: 700, fixity: "xfx"}},
                  ">:<": {infix:{precedence: 700, fixity: "xfx"}},
                  ":<": {infix:{precedence: 700, fixity: "xfx"}},
                  ":": {infix:{precedence: 600, fixity: "xfy"}},
                  "/\\": {infix:{precedence: 500, fixity: "yfx"}},
                  "\\/": {infix:{precedence: 500, fixity: "yfx"}},
                  "xor": {infix:{precedence: 500, fixity: "yfx"}},
                  "*": {infix:{precedence: 400, fixity: "yfx"}},
                  "/": {infix:{precedence: 400, fixity: "yfx"}},
                  "//": {infix:{precedence: 400, fixity: "yfx"}},
                  "rdiv": {infix:{precedence: 400, fixity: "yfx"}},
                  "<<": {infix:{precedence: 400, fixity: "yfx"}},
                  ">>": {infix:{precedence: 400, fixity: "yfx"}},
                  "mod": {infix:{precedence: 400, fixity: "yfx"}},
                  "rem": {infix:{precedence: 400, fixity: "yfx"}},
                  "**": {infix:{precedence: 200, fixity: "xfx"}},
                  "^": {infix:{precedence: 200, fixity: "xfy"}}};
